import turtle
t=turtle.Turtle()
turtle.bgcolor('black')
t.color('white')
t.speed(0)

def kwadrat(a,b,x,y):
    t.speed(0)
    t.penup()
    t.goto(x,y)
    t.pendown()
    t.setheading(0)
    t.color('magenta')
    t.begin_fill()

    for i in range(4):
        t.forward(a)
        t.right(b)

        
    t.end_fill()
    t.color('white')

def kwadraty():
    a=-900
    for i in range(5):
        kwadrat(100,90,a,-300)
        t.penup()    
        t.forward(a+150)
        t.pendown()

def trojkat():
    t.speed(0)
    t.penup()
    t.goto(600,-170)
    t.pendown()
    t.setheading(0)
    t.begin_fill()
    t.left(90)
    t.forward(300)
    t.right(135)
    t.forward(424)
    t.right(135)
    t.forward(300)
    t.end_fill()

    t.penup()
    t.goto(580,-170)
    t.pendown()
    t.setheading(180)
    t.begin_fill()
    t.forward(300)
    t.right(135)
    t.forward(424)
    t.right(135)
    t.forward(300)
    t.end_fill()

    t.penup()
    t.goto(580,-190)
    t.pendown() 
    t.setheading(180)
    t.begin_fill()
    t.left(90)
    t.forward(300)
    t.right(135)
    t.forward(424)
    t.right(135)
    t.forward(300)
    t.end_fill()

    t.penup()
    t.goto(600,-190)
    t.pendown()
    t.setheading(0)
    t.begin_fill()
    t.forward(300)
    t.right(135)
    t.forward(424)
    t.right(135)
    t.forward(300)
    t.end_fill()

def star():
    t.penup()
    t.goto(-200,-200)
    t.pendown()
    t.speed(0)
    t.color('yellow')
    t.setheading(0)
    for i in range(5):
        t.begin_fill()
        for i in range(5):
            t.forward(50)
            t.right(144)
        t.end_fill()
        t.penup()
        t.forward(100)
        t.left(70)
        t.forward(100)
        t.pendown()
    t.color('white')

def ring():
    t.speed(0)
    t.penup()
    t.goto(200,290)
    t.pendown()
    for i in range(4):
        t.setheading(90)   
        t.circle(100)
        t.penup()
        t.left(90)
        t.forward(30)
        t.pendown()
        t.right(90)
        t.circle(70)
        t.penup()
        t.setheading(0)
        t.forward(250)
        t.pendown()

def arrow():
    t.speed(0)
    t.penup()
    t.goto(-700,0)
    t.pendown()
    t.color('grey')
    t.begin_fill()
    for i in range(5):
        t.setheading(0)
        t.forward(150)
        t.left(90)
        t.forward(40)
        t.right(120)
        t.forward(110)
        t.right(120)
        t.forward(110)
        t.right(120)
        t.forward(40)
        t.left(90)
        t.forward(150)
        t.right(90)
        t.forward(30)
        t.penup()
        t.forward(111)
        t.pendown()
    t.end_fill()
    t.color('white')

def name():
    t.penup()
    t.goto(370,450)
    t.pendown()
    t.write('Bartłomiej Reguła, ZZISS1-1113', font=('Arial',30))

# arrow()
# kwadrat()
# trojkat()
# star()
# ring()
# name()
kwadraty()


turtle.exitonclick()